name: common_utils
description: Dart common utils library.Contain DateUtil, EncryptUtil, JsonUtil, LogUtil, MoneyUtil, NumUtil, ObjectUtil, RegexUtil, TextUtil, TimelineUtil, TimerUtil.
version: 2.1.0
homepage: https://github.com/Sky24n/common_utils

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rational: ^1.2.1
  decimal: ^1.5.0
  crypto: ^3.0.1
  convert: ^3.0.2